# Generated by Django 4.1 on 2022-10-31 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0004_alter_movie_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='currency',
            field=models.CharField(choices=[('EUR', 'euro'), ('USD', 'dollar'), ('RUB', 'rubles')], default='RUB', max_length=3),
        ),
    ]
