# Generated by Django 4.1 on 2022-10-31 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0008_movie_director'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='director_email',
            field=models.EmailField(default='не известен', max_length=60),
        ),
        migrations.AlterField(
            model_name='movie',
            name='director',
            field=models.CharField(default='не известен', max_length=60),
        ),
    ]
