# Generated by Django 4.1 on 2022-10-31 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0009_movie_director_email_alter_movie_director'),
    ]

    operations = [
        migrations.CreateModel(
            name='Direcor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(default='не известен', max_length=60)),
                ('lastname', models.CharField(default='не известен', max_length=60)),
                ('director_email', models.EmailField(default='не известен', max_length=60)),
            ],
        ),
        migrations.RemoveField(
            model_name='movie',
            name='director',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='director_email',
        ),
    ]
