# Generated by Django 4.1 on 2022-11-01 12:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0013_actor_movie_actors'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('holl', models.IntegerField(max_length=15)),
                ('room', models.IntegerField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='actor',
            name='room',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='movie_app.room'),
        ),
    ]
