# Generated by Django 4.1 on 2022-11-01 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0014_room_actor_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='director',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movies', to='movie_app.director'),
        ),
        migrations.AlterField(
            model_name='room',
            name='holl',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='room',
            name='room',
            field=models.IntegerField(),
        ),
    ]
